name: consulter_ui
description: A new Flutter project for Consulter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Paquetes actualizados a versiones recientes y compatibles
  go_router: ^14.2.0
  fluent_ui: ^4.9.0
  file_picker: ^8.0.5
  window_manager: ^0.3.9

  # UI and Core
  cupertino_icons: ^1.0.6

  # Networking
  http: ^1.2.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # JSON Serialization / Deserialization
  json_annotation: ^4.9.0

  # Local Storage for Session
  shared_preferences: ^2.2.3
  
  # Date formatting
  intl: ^0.20.2

  # Autocomplete
  textfield_tags: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1 
  build_runner: ^2.4.8 
  json_serializable: ^6.7.1 
  riverpod_generator: ^2.4.0 
  riverpod_lint: ^2.3.10 

flutter:
  uses-material-design: true